stages:
  - test
variables:
  CONDA_PKGS_DIRS: "$CI_PROJECT_DIR/.cache/conda"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

default:
  tags: [docker]
  image: continuumio/miniconda3:24.11.1-0
  cache:
    paths:
      - .cache/conda
      - .cache/pip
  before_script:
    - apt-get update && apt-get install -y libevdev2
    - conda install --channel=conda-forge --name=base conda-lock
    - conda-lock install -n pose-pie conda-lock.yml
    - conda init bash
    - source ~/.bashrc
    - conda activate pose-pie

black:
  stage: test
  script:
    - black --check --diff --color --line-length=140 --exclude ".cache" .

mypy:
  stage: test
  script:
    - mypy .

pytest:
  stage: test
  script:
    - pytest --junit-xml=report.xml --cov --cov-report term --cov-report xml:report_cov.xml --ignore=.cache
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: report_cov.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

